extend textController to support triggerStyles
acterglobal/a3 pull request #1987
Opened 2024-07-24 15:51 UTC by gtalha07

2024-07-24 17:17 UTC, gtalha07 commented on app/packages/multi_trigger_autocomplete/lib/src/autocomplete_controller.dart
> +class AutocompleteTextController extends TextEditingController {
This is the main class which extends ```TextEditingController``` to allow us build custom text spans based on trigger characters. ```triggerStyles``` is passed down here from main widget ```MultiTriggerAutoComplete```.

2024-07-24 17:21 UTC, gtalha07 commented on app/lib/features/chat/widgets/custom_input.dart
> +  late AutocompleteTextController controller;
This now replaces with extended controller ```AutocompleteTextController``` which takes ```triggerStyles```.

2024-07-24 17:22 UTC, gtalha07 commented on app/packages/multi_trigger_autocomplete/lib/src/autocomplete_trigger.dart
> +  AutocompleteTextController textEditingController,
just an update to replace ```TextEditingController``` to ```AutocompleteTextController```.

2024-07-24 17:23 UTC, gtalha07 commented on app/packages/multi_trigger_autocomplete/lib/src/multi_trigger_autocomplete.dart
> +  final Map<String, TextStyle>? triggerStyles;
Added param to take trigger word optional style.

2024-07-24 17:24 UTC, gtalha07 commented on app/packages/multi_trigger_autocomplete/lib/src/multi_trigger_autocomplete.dart
> +  final AutocompleteTextController textEditingController;
This is now required along with ```FocusNode```. And removed ```initialValue``` option.

2024-07-24 17:26 UTC, gtalha07 commented on app/packages/multi_trigger_autocomplete/test/multi_trigger_autocomplete_test.dart
> +void main() {
Here is just an update of taking required parameters along with ```AutocompleteTextController```.

2024-07-24 17:26 UTC, gtalha07 commented on app/pubspec.yaml
> +  multi_trigger_autocomplete:
Replaced mainstream with sub-project dependency.

2024-07-25 10:12 UTC, gnunicorn commented
@gtalha07 can you elaborate a bit more on the rational for this? Do I understand correctly that in order to do our wanted changes, we have to create a fork? These are not things the upstream project would want or expect in their version? Do you consider the project unmaintained?

2024-07-25 10:14 UTC, gnunicorn commented
another side note: it would have been nice if you had one commit to just import the project so that only the changes made could be reviewed easily. This is really not feasible to review now as all files and all lines are marked as new, so I don't know what you've changed ...

2024-07-25 10:24 UTC, gnunicorn requested changes
It's really hard to understand what should be reviewed and what should not. Can I ask that you change the history of what to be done here to:
 1. one commit that imports the existing project code, with superfluous stuff removed (the gifs)
 2. one commit to change the name and imports into our code base as is
 3. one or several other commits on top that do the changes on that code base and our app as necessary.

That makes for a cleaner importing of the project as well as for something I can actually review as I know what to look at ...

(you can also combine 1 and 2 if you prefer)

2024-07-25 16:24 UTC, gtalha07 commented
> @gtalha07 can you elaborate a bit more on the rational for this? Do I understand correctly that in order to do our wanted changes, we have to create a fork? These are not things the upstream project would want or expect in their version? Do you consider the project unmaintained?



> @gtalha07 can you elaborate a bit more on the rational for this? Do I understand correctly that in order to do our wanted changes, we have to create a fork? These are not things the upstream project would want or expect in their version? Do you consider the project unmaintained?

The fork is just there so it's easier to follow how the package is modified which I think might turn out completely different, more aligning to our requirements rather than plugin intended features. I don't think the changes followed here and after, would come up as extended version but rather , completely revised version of it with different way of handling more of the core stuff. Just as an example that I removed some params .i.e. ```initialValue``` and making some required .i.e. ```TextEditingController``` because without those change-set, the styling won't work. I don't consider project unmaintained though. But the way it's structured, it's hard to expect that without major refactoring, it'd come up near close to what I envisioned...

Still I'm open to feedback of how we can structure this version so it doesn't conflict or make it more overshadowed than original but come out as wholly new standalone, based on whole different mechanism but can provide way of extensify features.

2024-07-25 16:26 UTC, closed without merging

2024-07-25 17:32 UTC, gnunicorn commented
@gtalha07  Thanks for explaining the why. I'm okay with maintaining a fork in the repo. Looking forward to a more cleaned up version to do the same :) .