General fixes related to Time Format and Event Time UI
acterglobal/a3 pull request #2120
Opened 2024-08-29 12:21 UTC by kumarpalsinh25

fixes, https://github.com/acterglobal/a3/issues/2087
fixes, https://github.com/acterglobal/a3-meta/issues/483

### 12 Hour Format:

https://github.com/user-attachments/assets/28b71334-b00b-4490-afd5-6fe6a1f80beb

### 24 Hour Format:

https://github.com/user-attachments/assets/585d8bdb-efee-4257-9211-9ad2a445c130

2024-08-29 15:44 UTC, gnunicorn requested changes
Not convinced this is the right fix. It looks right, but shouldn't we instead be doing a proper `initializeDateFormatting` from `intl` and just use the time system it then formats with?

Reading a bit more of the used `alwaysUse24HourFormat` it indeed seems to not be reliable, as on Android it is only set if the user explictly said so, but not if only the locale would dictate that. Thus for a continental European Android without the user actively changing the setting, we'd still show the wrong time format.

2024-08-29 15:44 UTC, gnunicorn commented on app/lib/common/utils/utils.dart
> +    return is24HoursFormat ? jiffyTime.Hm : jiffyTime.jm;
this seems like a rather convoluted way of doing
`DateFormat.jm().format(localDateTime));` (from the `intl` package we already have included anyways) 

Any reason for not just using [`Intl.DateFormat`](https://api.flutter.dev/flutter/intl/DateFormat-class.html)?

2024-08-29 15:44 UTC, gnunicorn commented on app/lib/features/chat/pages/room_page.dart
> +        timeFormat: is24HoursFormat ? DateFormat.Hm() : DateFormat.jm(),
so, I see... it looks like DateFormat isn't set up to use the right `local` ... shouldn't we rather be fixing that problem then?

2024-08-30 07:58 UTC, kumarpalsinh25 commented
@gnunicorn 
I tried `initializeDateFormatting` from `intl` and use the default `DateFormat` behavior earlier also but getting 24 hour format event though I select European region from system while testing.

I am not sure I did any mistake on Testing this feature. I have did correction based on default behavior as suggested and [committed code here](https://github.com/acterglobal/a3/pull/2120/commits/ca8c151d02147aaefaca920b0391b79f3adfee09).

Can you please review it and check it I did anything wrong or it all we want.

2024-08-30 08:01 UTC, kumarpalsinh25 commented
@gnunicorn 
Also I would to like to request you to run this branch code on your system and see if time is showing in 24 hours or not.

2024-08-30 09:30 UTC, gnunicorn commented
@kumarpalsinh25 ahahahah

![image](https://github.com/user-attachments/assets/749320a5-6890-41c9-b5e1-4f4079023af7)


Yeah, it doesn't integrate with our locale/language setting yet. I guess we should just set the system locale?!?

2024-08-30 10:00 UTC, gnunicorn commented
@kumarpalsinh25 I've pushed a commit to the branch setting `Intl.defaultLocale` depending on the language the user selected. Leading to the following behavior, which is what we want, I think:


https://github.com/user-attachments/assets/b161e9dc-9504-4482-bb8b-691e9721d5e7

2024-08-30 10:02 UTC, gnunicorn commented
and Arabic, too (not as if I can confirm this being correct, but ...)

![image](https://github.com/user-attachments/assets/4225cfbe-da79-4cfa-ac15-8fb9359e8c08)

2024-08-30 10:05 UTC, gnunicorn approved these changes
as per my change it does what I'd expect, so I'd approve :D

2024-08-30 10:14 UTC, kumarpalsinh25 commented
> @kumarpalsinh25 ahahahah
> Yeah, it doesn't integrate with our locale/language setting yet. I guess we should just set the system locale?!?

Haven't find anything related this in https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

Let me check more details about the same.

2024-08-30 10:16 UTC, kumarpalsinh25 commented on app/lib/features/settings/providers/notifiers/locale_notifier.dart
> +}
Ah I see, so this was the missing part?

2024-08-30 10:21 UTC, merged