Acter Icon Picker implementation and Integrate it with Create Pin
acterglobal/a3 pull request #2143
Opened 2024-09-04 08:01 UTC by kumarpalsinh25

https://github.com/user-attachments/assets/da54b861-95c1-476a-a95a-2bdc9972ceed

2024-09-05 08:32 UTC, kumarpalsinh25 reviewed
Added few comments which might be helpful during PR review.

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/common/widgets/acter_icon_picker/acter_icon_widget.dart
> +class ActerIconWidget extends StatefulWidget {
This class is for generic ActerIcon widget which is used in multiple places like list item, edit/selection mode on creation form etc.. 


1) Used in Pin Create Form:
![Screenshot 2024-09-05 at 1 49 47 PM](https://github.com/user-attachments/assets/b46d10ed-d96c-4293-90fa-e80dcf3456fb)

2) Used in PinList Item:
![Screenshot 2024-09-05 at 1 50 53 PM](https://github.com/user-attachments/assets/c1808d47-04e9-4f72-a3a8-94ca47a61be5)

3) Used in Pin Detail screen:
![Screenshot 2024-09-05 at 1 51 27 PM](https://github.com/user-attachments/assets/bcaf652d-9574-49f5-ab7b-3abb9087e21a)

4) Used in TaskList Create Form:
![Screenshot 2024-09-05 at 1 50 06 PM](https://github.com/user-attachments/assets/8aacc624-2c8b-4d6f-b279-724930b0545d)

5) Used in TaskList Item:
![Screenshot 2024-09-05 at 1 52 37 PM](https://github.com/user-attachments/assets/ffd92300-93d4-4791-8590-e044ce5969da)

6) Used in TaskList Detail screen:
![Screenshot 2024-09-05 at 1 52 48 PM](https://github.com/user-attachments/assets/18baa7cc-91a4-486e-849a-cf8c3f251c08)

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/common/widgets/acter_icon_picker/model/acter_icons.dart
> +enum ActerIcons {
This contains set of ActorIcons data.

![Screenshot 2024-09-05 at 1 55 06 PM](https://github.com/user-attachments/assets/bea3f45d-5c34-4363-aa35-8db4d90869f3)

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/common/widgets/acter_icon_picker/model/color_data.dart
> +List<Color> iconPickerColors = [
This contains set of ActerIcons Colors.

![Screenshot 2024-09-05 at 1 54 51 PM](https://github.com/user-attachments/assets/63da8d3d-df50-446e-986f-2a994c29009f)

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/common/widgets/acter_icon_picker/picker/acter_icon_picker.dart
> +class ActerIconPicker extends StatefulWidget {
This class is for ActerIcon Picker.
- It is manage as independent Component which can be reused based on the requirement.
- For shake of simplicity, Entire picker states are managed by basic `ValueNotifier` entire state management kept within class and avoided providers here to make it more independent widget.

![Screenshot 2024-09-05 at 1 56 03 PM](https://github.com/user-attachments/assets/62805148-b601-4cae-98cb-813272fee7b3)

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/features/pins/Utils/pins_utils.dart
> +Future<void> savePinIcon(
This is to update Icon Widget from Pin Details Page.

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/features/pins/pages/create_pin_page.dart
> +                        child: ActerIconWidget(
This is how generic `ActerIconWidget` used with simplest code.

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/features/pins/pages/create_pin_page.dart
> +      // Pin IconData
This is to add Pin Icon data white pin creation.

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/features/pins/widgets/pin_list_item_widget.dart
> +        leading: ActerIconWidget(
Reused the same `ActerIconWidget` in list item as view only widget.

2024-09-05 08:32 UTC, kumarpalsinh25 commented on app/lib/features/tasks/pages/task_list_details_page.dart
> +      data: (tasklist) {
Just added `ActerIconWidget` in app bar and manage it's edit right based on the membership.

2024-09-05 10:17 UTC, gnunicorn commented
_UX discussion_:
I've looked at the video several times now and I am unsure about the size of the icons. I think I've mentioned before that I think showing them that much larger in the editing than in the actual view isn't great UX as it gives you the wrong impression on how it will be perceived by the others - but that is negligible, as you will see it soon enough and can change it if you want.

But in the list itself. I know you love the apple lists, but I find those icons pretty intense, with its size that is twice the title and then comes with strong colors. That is rather far away from the "little sprinkles of color" I imagined and proposed.

Take this random screenshot from Notion for comparison
![image](https://github.com/user-attachments/assets/8ea943f4-7d76-4afe-b15b-fe01c149b095)

Sure, there it's emoji and they are more detailed and colorful, but none is larger than the texts it belongs to and just acts as _a guide_ not as the primary attention grabbing item.

I feel those icons in this UI grab _a lot_ of attention (in particular because everything else is now monochrome) -- too much IMHO, as they _don't guide_ the users UI over the different items but _grab the attention_ and hold onto it, making it actually _harder_ to parse the text next to them ....

2024-09-05 11:03 UTC, gnunicorn requested changes
Code-wise very nice. But we need not submit an icon and a color if the user hasn't diverted from the default. That needs to be supported before we merge this to not pollute the data that users submit...

2024-09-05 11:03 UTC, gnunicorn commented on app/lib/features/tasks/actions/update_tasklist.dart
> +    ActerIcons acterIcon,
should be optional, too.

2024-09-05 11:04 UTC, gnunicorn commented
> I feel those icons in this UI grab a lot of attention (in particular because everything else is now monochrome) -- too much IMHO, as they don't guide the users UI over the different items but grab the attention and hold onto it, making it actually harder to parse the text next to them ....

I wonder if we might want to use the color as a foreground color of the icon rather than the background of the even larger badge... I think that might be enough to fix these UX problems I have with it.

2024-09-05 11:06 UTC, kumarpalsinh25 commented
@gnunicorn 
ICON SIZE:
Notion using emojis and we have icons in current stuff which have background circle. Due to background circle it will not look so good if we reduce icon size too small. Still I have reduce icon size at some level. Check below video for the same.


https://github.com/user-attachments/assets/5d5798e5-102b-4f03-a988-ff81def5d6e4

Happy to do further changes if needed. :)

2024-09-05 11:11 UTC, kumarpalsinh25 commented
> > I feel those icons in this UI grab a lot of attention (in particular because everything else is now monochrome) -- too much IMHO, as they don't guide the users UI over the different items but grab the attention and hold onto it, making it actually harder to parse the text next to them ....
> 
> I wonder if we might want to use the color as a foreground color of the icon rather than the background of the even larger badge... I think that might be enough to fix these UX problems I have with it.


Yes that can be done. 
![Screenshot 2024-09-05 at 4 39 43 PM](https://github.com/user-attachments/assets/5c788aea-5472-4703-93b6-568141b88511)


Probably for this I need to change some colors and selecte some brighter variant. But take a note that in future when we give support for light theme then it might create issue.

2024-09-05 11:22 UTC, gnunicorn commented
> Probably for this I need to change some colors and selected some brighter variant.

yeah, the screenshot is a lot easier to parse I think. I prefer that. We might want to change the default color as though and maybe in that case increasing the icon size as we have very thin icons? 

would love to get @emilvincentz 's feedback on this.


> But take a note that in future when we give support for light theme then it might create issue.

Light theme doesn't have priority. But even then I can easily imagine just using the color as a background or derive another background from that foreground to create enough contrast is enough.

2024-09-05 11:49 UTC, kumarpalsinh25 commented
@gnunicorn 
General PR Feedback Work:

- Name correction:
https://github.com/acterglobal/a3/pull/2143/commits/850a7d9e8c3251df66e1955ef4568504a8c75b17

- Missing language translation:
https://github.com/acterglobal/a3/pull/2143/commits/043793af6456c614a5f87625d9a286e22aa1fa34

- Arrange pin actions into relevant file and folder:
https://github.com/acterglobal/a3/pull/2143/commits/d5088b10419f0370b0d978222f5c6019f2f359d1

- Minor wording correction:
https://github.com/acterglobal/a3/pull/2143/commits/abd2a188b68efdfc17db1feea1f7bfa4ca34affc

- Make icon and color optional by default and don't pass it if user haven't select it.
https://github.com/acterglobal/a3/pull/2143/commits/d4c77a747fae2c5184a1ab345292f3cc50f1f793

2024-09-05 11:52 UTC, kumarpalsinh25 commented
@gnunicorn 
This how it will look if we remove icon background.


https://github.com/user-attachments/assets/4eeba10b-dd29-4627-ab25-9facc5cc8778

2024-09-05 12:45 UTC, gnunicorn commented
> This how it will look if we remove icon background.

I like it. What do you think, @emilvincentz ?

2024-09-05 13:05 UTC, emilvincentz commented
Well I dont have the strongest options. 

As I see it:

Pros of without background colour:
- More subtle

Pros with background colour:
-  that you can use the colour indication for e.g. prioritisation or clustering. Like you woul have two objects with same icon, but use the colour to indicate some kind of status or importance. 

However my main and first thought was, that we just want to make sure that it's easy for the user to know what is pins and what is tasks. Right now there is a small chance that the you scroll over it, you maybe dont realize that one list is tasks and the other is pins, as they look like each other.

But overall, I think both looks good. 

But with these things, I would take a quick screen shot and share in the team channel to get their perspective 
or in the future also put it into the product update channel and see if anyone engages;)

2024-09-06 06:43 UTC, kumarpalsinh25 commented
@emilvincentz @gnunicorn 
Here we go with final version as per given suggestions....
- Remove circle background and applied color on Icon directly
- Did needful changes on icon size accordingly
- Added more brighter (Accent variant) colors for better contrast

Reference Video:

https://github.com/user-attachments/assets/a260e48c-e4f8-4fd2-b88d-507a67b564c0

@gnunicorn 
Can you resolve conflict related to `rendering.rs` and gets this PR to merge?

2024-09-06 12:20 UTC, kumarpalsinh25 commented
> Just noticed, at pos 0:40 of the video the icon preview switches back to the wrong one ... you might want to fix that before we merge ...

- I also notice this after uploading video in PR Description and already fixed it by [this commit.](https://github.com/acterglobal/a3/pull/2143/commits/5fdc253bd1e9a3e5a3d52fcf2e6ccd8a2f09ac27). Just haven't did new screen recording :)

> and it appears, the unit tests for pins needs fixing now...

I also check this error but not getting much idea, let me check it in more detail.

2024-09-06 12:29 UTC, kumarpalsinh25 commented on app/lib/features/pins/pages/create_pin_page.dart
> +                          icon: pinIcon ?? ActerIcon.pin,
@gnunicorn 
This fixes the issue seeing in video at time 00:40.

2024-09-06 13:10 UTC, merged