Bug Fixes
acterglobal/a3 pull request #779
Opened 2023-07-21 07:22 UTC by kokodavid

Pin creation space field UI bugs and Creation sheets CTA button fixes.

2023-07-21 09:56 UTC, gnunicorn requested changes
Thanks, mate.

I have some minor clean up requests, and could you please add a file in `.changes` documenting what you fixed for end-users, like [described here in our docs](https://docs.acter.global/docs/contributing/reviews/#tracking-changes), please!?!

2023-07-21 09:56 UTC, gnunicorn commented on app/lib/features/events/dialogs/create_event_sheet.dart
> +            //     : Theme.of(context).colorScheme.success.withOpacity(0.6),
why are we committing commented lines? Please remove.
```suggestion
```

2023-07-21 09:56 UTC, gnunicorn commented on app/lib/features/news/pages/simple_post.dart
> +            //     : Theme.of(context).colorScheme.success.withOpacity(0.6),
same.
```suggestion
```

2023-07-21 09:56 UTC, gnunicorn commented on app/lib/features/pins/dialogs/create_pin_sheet.dart
> +            //     : Theme.of(context).colorScheme.success.withOpacity(0.6),
```suggestion
```

2023-07-21 09:56 UTC, gnunicorn commented on app/lib/features/pins/dialogs/create_pin_sheet.dart
> +              // ),
```suggestion
```

2023-07-21 09:56 UTC, gnunicorn commented on app/lib/features/pins/dialogs/create_pin_sheet.dart
> +                  onTap: ()async{
style

```suggestion
                  onTap: () async {
```

2023-07-24 07:11 UTC, kokodavid commented
@gnunicorn 

Thanks for the review , I have made the changes requested and also created the .changes folder and created a file '779-fixes.md' . I just want to confirm if that's the correct way before I push the changes . Kindly let me know if it's correct .
![image](https://github.com/acterglobal/a3/assets/47295684/f7041259-b2cf-4fd5-8d68-4959dac96257)

2023-07-24 12:34 UTC, gnunicorn approved these changes

2023-07-24 12:34 UTC, merged